export const SEARCH_RESPOSITORIES         = 'SEARCH_RESPOSITORIES'
export const SUCCESS_SEARCH_RESPOSITORIES = 'SUCCESS_SEARCH_RESPOSITORIES'
export const ERROR_SEARCH_RESPOSITORIES   = 'ERROR_SEARCH_RESPOSITORIES'